src/Entity/Carte.php
<?php

namespace App\Entity;

use App\Repository\CarteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=CarteRepository::class)
 */
class Carte
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $num_card;

    /**
     * @ORM\Column(type="date")
     */
    private $dCard_endVal;

    /**
     * @ORM\Column(type="boolean")
     */
    private $card_val;

    /**
     * @ORM\ManyToMany(targetEntity=Cimetiere::class, mappedBy="carteAcces")
     */
    private $cimetieres;

    public function __construct()
    {
        $this->cimetieres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumCard(): ?string
    {
        return $this->num_card;
    }

    public function setNumCard(string $num_card): self
    {
        $this->num_card = $num_card;

        return $this;
    }

    public function getDCardEndVal(): ?\DateTimeInterface
    {
        return $this->dCard_endVal;
    }

    public function setDCardEndVal(\DateTimeInterface $dCard_endVal): self
    {
        $this->dCard_endVal = $dCard_endVal;

        return $this;
    }

    public function getCardVal(): ?bool
    {
        return $this->card_val;
    }

    public function setCardVal(bool $card_val): self
    {
        $this->card_val = $card_val;

        return $this;
    }

    /**
     * @return Collection|Cimetiere[]
     */
    public function getCimetieres(): Collection
    {
        return $this->cimetieres;
    }

    public function addCimetiere(Cimetiere $cimetiere): self
    {
        if (!$this->cimetieres->contains($cimetiere)) {
            $this->cimetieres[] = $cimetiere;
            $cimetiere->addCarteAcce($this);
        }

        return $this;
    }

    public function removeCimetiere(Cimetiere $cimetiere): self
    {
        if ($this->cimetieres->removeElement($cimetiere)) {
            $cimetiere->removeCarteAcce($this);
        }

        return $this;
    }
}

src/Entity/Utilisateurs.php
<?php

namespace App\Entity;

use App\Repository\UtilisateursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=UtilisateursRepository::class)
 */
class Utilisateurs
{
    /**
     * Hook blameable behavior
     * updates createdBy, updatedBy fields
     */
    use BlameableEntity;

    /**
     * Hook timestampable behavior
     * updates createdAt, updatedAt fields
     */
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomFam_ut;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nomUs_ut;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pre_ut;

    /**
     * @ORM\Column(type="date")
     */
    private $dayBirth_ut;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstAdress_ut;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $compAdress_ut;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city_ut;

    /**
     * @ORM\Column(type="integer")
     */
    private $cp_ut;

    /**
     * @ORM\ManyToMany(targetEntity=Gestionnaire::class, mappedBy="gere")
     */
    private $gestionnaires;

    /**
     * @ORM\OneToOne(targetEntity=Carte::class, cascade={"persist", "remove"})
     */
    private $possede;


    public function __construct()
    {
        $this->gestionnaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFamUt(): ?string
    {
        return $this->nomFam_ut;
    }

    public function setNomFamUt(string $nomFam_ut): self
    {
        $this->nomFam_ut = $nomFam_ut;

        return $this;
    }

    public function getNomUsUt(): ?string
    {
        return $this->nomUs_ut;
    }

    public function setNomUsUt(?string $nomUs_ut): self
    {
        $this->nomUs_ut = $nomUs_ut;

        return $this;
    }

    public function getPreUt(): ?string
    {
        return $this->pre_ut;
    }

    public function setPreUt(string $pre_ut): self
    {
        $this->pre_ut = $pre_ut;

        return $this;
    }

    public function getDayBirthUt(): ?\DateTimeInterface
    {
        return $this->dayBirth_ut;
    }

    public function setDayBirthUt(\DateTimeInterface $dayBirth_ut): self
    {
        $this->dayBirth_ut = $dayBirth_ut;

        return $this;
    }

    public function getFirstAdressUt(): ?string
    {
        return $this->firstAdress_ut;
    }

    public function setFirstAdressUt(string $firstAdress_ut): self
    {
        $this->firstAdress_ut = $firstAdress_ut;

        return $this;
    }

    public function getCompAdressUt(): ?string
    {
        return $this->compAdress_ut;
    }

    public function setCompAdressUt(?string $compAdress_ut): self
    {
        $this->compAdress_ut = $compAdress_ut;

        return $this;
    }

    public function getCityUt(): ?string
    {
        return $this->city_ut;
    }

    public function setCityUt(string $city_ut): self
    {
        $this->city_ut = $city_ut;

        return $this;
    }

    public function getCpUt(): ?int
    {
        return $this->cp_ut;
    }

    public function setCpUt(int $cp_ut): self
    {
        $this->cp_ut = $cp_ut;

        return $this;
    }

    /**
     * @return Collection|Gestionnaire[]
     */
    public function getGestionnaires(): Collection
    {
        return $this->gestionnaires;
    }

    public function addGestionnaire(Gestionnaire $gestionnaire): self
    {
        if (!$this->gestionnaires->contains($gestionnaire)) {
            $this->gestionnaires[] = $gestionnaire;
            $gestionnaire->addGere($this);
        }

        return $this;
    }

    public function removeGestionnaire(Gestionnaire $gestionnaire): self
    {
        if ($this->gestionnaires->removeElement($gestionnaire)) {
            $gestionnaire->removeGere($this);
        }

        return $this;
    }

    public function getPossede(): ?Carte
    {
        return $this->possede;
    }

    public function setPossede(?Carte $possede): self
    {
        $this->possede = $possede;

        return $this;
    }
}

src/Form/SearchForm.php
<?php

namespace App\Form;

use App\Data\SearchData;
use App\Entity\Cimetiere;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SearchForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prenoms', TextType::class, [
                'label'=> 'Prénoms :',
                'required'=> false,
                'attr'=> [
                    'placeholder' => 'Prénoms'
                ]
            ])
            ->add( 'nomFam', TextType::class,[
                'label' => 'Nom de famille :',
                'required'=> false,
                'attr'=>[
                    'placeholder' => 'Nom de famille'
                ]
            ])

            ->add('nomUsa', TextType::class, [
                'label' => 'Nom d\'usage :',
                'required' =>false,
                'attr'=>[
                    'placeholder' => 'Nom d\'usage'
                ]
            ])

            ->add('birth',DateType::class,[
                'label'=>'Date de naissance :',
                'required' =>false,
                'widget'=>'single_text'
            ])

            ->add('cimetieres', EntityType::class, [
                'label'=> 'Cimetieres :',
                'required' => false,
                'class' => Cimetiere::class,
                'expanded' => true,
                'multiple' => true
            ])

        ;
    }


    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'=> SearchData::class,
            'method'=> 'GET',
            'csrf_protection' => false
        ]);
    }

    public function getBlockPrefix()
    {
        return '';
    }

}

src/Controller/SearchController.php
<?php

namespace App\Controller;

use App\Data\SearchData;
use App\Form\SearchForm;
use App\Repository\UtilisateursRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SearchController extends AbstractController
{
    /**
     * @Route("/search", name="search")
     */
    public function index(UtilisateursRepository $repository, Request $request): Response
    {
        $data = new SearchData();
        $form = $this->createForm(SearchForm::class, $data);
        $form->handleRequest($request);
        $user = $repository->findSearch($data);

        return $this->render('search/search.html.twig', [
            'users' => $user,
            'form' => $form->createView()
        ]);
    }
}

templates/search/_recherche.html.twig
    {{ form_start(form) }}

        {{ form_row(form.prenoms) }}
        {{ form_row(form.nomFam) }}
        {{ form_row(form.nomUsa) }}
        {{ form_row(form.birth) }}

        <button type="submit" class="btn btn-primary">Rechercher</button>
    {{ form_end(form) }}

templates/search/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateurs{% endblock %}

{% block body %}
    {% include '/header.html.twig' %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                {% include 'search/_recherche.html.twig' with {form: form} only %}
            </div>

            <div class="col-md-9">
                <div class="grid">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Identifiant </th>
                            <th>Prénoms </th>
                            <th>Nom de famille </th>
                            <th>Date de naissance </th>
                            <th>Identifiant carte </th>
                            <th>Validité </th>
                            <th>actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in users %}
                            <tr>
                                <td>{{ user.id }}</td>
                                <td>{{ user.preUt }}</td>
                                <td>{{ user.nomFamUt }}</td>
                                <td>{{ user.dayBirthUt ? user.dayBirthUt|date('Y-m-d') : ''  }}</td>
                                <td>{{ user.possede.id }}</td>

                                {% if user.possede.cardVal == true %}
                                    <td style="background-color: green">
                                        {{ user.possede.dcardEndVal ? user.possede.dcardEndVal|date('y-m-d') : '' }}
                                    </td>
                                {% else %}
                                    <td style="background-color: red">
                                        {{ user.possede.cardVal }}
                                    </td>
                                {% endif %}

                                <td>
                                    <a href="{{ path('utilisateurs_show', {'id': user.id}) }}">Voir Fiche</a>
                                    <a href="{{ path('utilisateurs_edit', {'id': user.id}) }}">Modifier</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

{% endblock %}