src/Entity/Carte.php
<?php

namespace App\Entity;

use App\Repository\CarteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=CarteRepository::class)
 */
class Carte
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $num_card;

    /**
     * @ORM\Column(type="date")
     */
    private $dCard_endVal;

    /**
     * @ORM\Column(type="boolean")
     */
    private $card_val;

    /**
     * @ORM\ManyToMany(targetEntity=Cimetiere::class, mappedBy="carteAcces")
     */
    private $cimetieres;

    public function __construct()
    {
        $this->cimetieres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumCard(): ?string
    {
        return $this->num_card;
    }

    public function setNumCard(string $num_card): self
    {
        $this->num_card = $num_card;

        return $this;
    }

    public function getDCardEndVal(): ?\DateTimeInterface
    {
        return $this->dCard_endVal;
    }

    public function setDCardEndVal(\DateTimeInterface $dCard_endVal): self
    {
        $this->dCard_endVal = $dCard_endVal;

        return $this;
    }

    public function getCardVal(): ?bool
    {
        return $this->card_val;
    }

    public function setCardVal(bool $card_val): self
    {
        $this->card_val = $card_val;

        return $this;
    }

    /**
     * @return Collection|Cimetiere[]
     */
    public function getCimetieres(): Collection
    {
        return $this->cimetieres;
    }

    public function addCimetiere(Cimetiere $cimetiere): self
    {
        if (!$this->cimetieres->contains($cimetiere)) {
            $this->cimetieres[] = $cimetiere;
            $cimetiere->addCarteAcce($this);
        }

        return $this;
    }

    public function removeCimetiere(Cimetiere $cimetiere): self
    {
        if ($this->cimetieres->removeElement($cimetiere)) {
            $cimetiere->removeCarteAcce($this);
        }

        return $this;
    }
}

src/Entity/Utilisateurs.php
<?php

namespace App\Entity;

use App\Repository\UtilisateursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=UtilisateursRepository::class)
 */
class Utilisateurs
{
    /**
     * Hook blameable behavior
     * updates createdBy, updatedBy fields
     */
    use BlameableEntity;

    /**
     * Hook timestampable behavior
     * updates createdAt, updatedAt fields
     */
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomFam_ut;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nomUs_ut;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pre_ut;

    /**
     * @ORM\Column(type="date")
     */
    private $dayBirth_ut;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstAdress_ut;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $compAdress_ut;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city_ut;

    /**
     * @ORM\Column(type="integer")
     */
    private $cp_ut;

    /**
     * @ORM\ManyToMany(targetEntity=Gestionnaire::class, mappedBy="gere")
     */
    private $gestionnaires;

    /**
     * @ORM\OneToOne(targetEntity=Carte::class, cascade={"persist", "remove"})
     */
    private $possede;


    public function __construct()
    {
        $this->gestionnaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFamUt(): ?string
    {
        return $this->nomFam_ut;
    }

    public function setNomFamUt(string $nomFam_ut): self
    {
        $this->nomFam_ut = $nomFam_ut;

        return $this;
    }

    public function getNomUsUt(): ?string
    {
        return $this->nomUs_ut;
    }

    public function setNomUsUt(?string $nomUs_ut): self
    {
        $this->nomUs_ut = $nomUs_ut;

        return $this;
    }

    public function getPreUt(): ?string
    {
        return $this->pre_ut;
    }

    public function setPreUt(string $pre_ut): self
    {
        $this->pre_ut = $pre_ut;

        return $this;
    }

    public function getDayBirthUt(): ?\DateTimeInterface
    {
        return $this->dayBirth_ut;
    }

    public function setDayBirthUt(\DateTimeInterface $dayBirth_ut): self
    {
        $this->dayBirth_ut = $dayBirth_ut;

        return $this;
    }

    public function getFirstAdressUt(): ?string
    {
        return $this->firstAdress_ut;
    }

    public function setFirstAdressUt(string $firstAdress_ut): self
    {
        $this->firstAdress_ut = $firstAdress_ut;

        return $this;
    }

    public function getCompAdressUt(): ?string
    {
        return $this->compAdress_ut;
    }

    public function setCompAdressUt(?string $compAdress_ut): self
    {
        $this->compAdress_ut = $compAdress_ut;

        return $this;
    }

    public function getCityUt(): ?string
    {
        return $this->city_ut;
    }

    public function setCityUt(string $city_ut): self
    {
        $this->city_ut = $city_ut;

        return $this;
    }

    public function getCpUt(): ?int
    {
        return $this->cp_ut;
    }

    public function setCpUt(int $cp_ut): self
    {
        $this->cp_ut = $cp_ut;

        return $this;
    }

    /**
     * @return Collection|Gestionnaire[]
     */
    public function getGestionnaires(): Collection
    {
        return $this->gestionnaires;
    }

    public function addGestionnaire(Gestionnaire $gestionnaire): self
    {
        if (!$this->gestionnaires->contains($gestionnaire)) {
            $this->gestionnaires[] = $gestionnaire;
            $gestionnaire->addGere($this);
        }

        return $this;
    }

    public function removeGestionnaire(Gestionnaire $gestionnaire): self
    {
        if ($this->gestionnaires->removeElement($gestionnaire)) {
            $gestionnaire->removeGere($this);
        }

        return $this;
    }

    public function getPossede(): ?Carte
    {
        return $this->possede;
    }

    public function setPossede(?Carte $possede): self
    {
        $this->possede = $possede;

        return $this;
    }
}

src/Form/UtilisateursType.php
<?php

namespace App\Form;

use App\Entity\Carte;
use App\Entity\CimAm;
use App\Entity\Cimetiere;
use App\Entity\Utilisateurs;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\ChoiceList\ChoiceList;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UtilisateursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nomFam_ut',TextType::class,[
                'label'=>'Nom de famille :'
            ])
            ->add('nomUs_ut',TextType::class,[
                'label'=>'Nom d\'usage :',
                'required' => false
            ])
            ->add('pre_ut',TextType::class,[
        'label'=>'Prénoms :'
            ])
            ->add('dayBirth_ut',DateType::class,[
                'label'=>'Date de naissance :',
                'widget'=>'single_text'
            ])
            ->add('firstAdress_ut',TextType::class,[
                'label'=>'Adresse princiale :'
            ])
            ->add('compAdress_ut',TextType::class,[
                'label'=>'Complément d\'adresse :',
                'required'=> false
            ])
            ->add('city_ut',TextType::class,[
                'label'=>'Ville :'
            ])
            ->add('cp_ut',TextType::class,[
                'label'=>'Code postale :'
            ])
            ->add('id_card', TextType::class,[
                'data'=> uniqid(),
                'label'=>'Numéro de carte :',
                'disabled'=>true,
                'mapped'=>false
            ])
            ->add('cardVal', CheckboxType::class,[
                'mapped'=>false,
                'required'=>false,
                'label'=> 'Validité :'
            ])

            ->add('cimetieres', EntityType::class, [
               'label'=> 'Accés cimetières :',
              'required' => false,
             'mapped' => false,
            'class' => Cimetiere::class,
            'expanded' => true,
            'multiple' => true,
            ])

            #->add('createdAt')
            #->add('updatedAt')
            #->add('gestionnaires')
            #->add('possede')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Utilisateurs::class,
        ]);
    }
}

src/Controller/UtilisateursController.php
<?php

namespace App\Controller;

use App\Data\SearchData;
use App\Entity\Carte;
use App\Entity\CimAm;
use App\Entity\Cimetiere;
use App\Entity\Gestionnaire;
use App\Entity\Utilisateurs;
use App\Form\SearchForm;
use App\Form\UtilisateursType;
use App\Repository\CarteRepository;
use App\Repository\CimetiereRepository;
use App\Repository\UtilisateursRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Date;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/utilisateurs")
 */
class UtilisateursController extends AbstractController
{
    /**
     * @Route("/", name="utilisateurs_index", methods={"GET"})
     */
    public function index(UtilisateursRepository $utilisateursRepository, CarteRepository $carteRepository, CimetiereRepository $cimetiereRepository): Response
    {
        return $this->render('utilisateurs/index.html.twig', [
            'utilisateurs' => $utilisateursRepository->findAll(),
            'carte'=> $carteRepository->findAll(),
            'cim' => $cimetiereRepository->findAll(),
        ]);

    }

    /**
     * @Route("/new", name="utilisateurs_new", methods={"GET","POST"})
     *
     */
    public function new(Request $request, EntityManagerInterface $entityManager, CimetiereRepository $cimetiereRepository, CarteRepository $carteRepository): Response
    {

        $utilisateur = new Utilisateurs();
        $card = new Carte();
        $gest = new Gestionnaire();


        $form = $this->createForm(UtilisateursType::class, $utilisateur);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $utilisateur->setCreatedAt(new  \DateTime());
            $utilisateur->setUpdatedAt(new \DateTime());
            $utilisateur->setUpdatedBy($gest->getIdenGes());
            $utilisateur->setCreatedBy($gest->getIdenGes());
            $utilisateur->setPossede($card);


            $card->setCardVal($form->get("cardVal")->getData());



            $card->setDCardEndVal(new \DateTime());



            $card->setNumCard($form->get("id_card")->getData());



            /**insertion de l'id de la carte dans les cimetières*/

            $selectedCimetiere = $form->get("cimetieres")->getData();
            foreach ($selectedCimetiere as $cim){
                $cimetiereEntity = $cimetiereRepository->find($cim);
                $card->addCimetiere($cimetiereEntity);
            }

            /** persistance des données et push dans la base données */
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($utilisateur);
            $entityManager->persist($card);
            $entityManager->flush();


            $this->addFlash('sucess',"Le nouvelle utilisateur a bien été enregistré !");

            return $this->redirectToRoute('utilisateurs_new', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('utilisateurs/new.html.twig', [
            'registrationForm'=> $form->createView()
        ]);

    }

    /**
     * @Route("/{id}", name="utilisateurs_show", methods={"GET"})
     */
    public function show(Utilisateurs $utilisateur): Response
    {
        return $this->render('utilisateurs/show.html.twig', [
            'utilisateur' => $utilisateur,
        ]);
    }

    /*
     * TODO : Je suis à ce point !!! Flashmessage pour generer les success aprés update
     */

    /**
     * @Route("/{id}/edit", name="utilisateurs_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Utilisateurs $utilisateur): Response
    {
        $form = $this->createForm(UtilisateursType::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('utilisateurs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('utilisateurs/edit.html.twig', [
            'utilisateur'=> $utilisateur,
            'registrationForm'=> $form->createView()
        ]);

        //return $this->renderForm('utilisateurs/edit.html.twig', [
          //  'utilisateur' => $utilisateur,
            //'form' => $form,
        //]);
    }

    /**
     * @Route("/{id}", name="utilisateurs_delete", methods={"POST"})
     */
    public function delete(Request $request, Utilisateurs $utilisateur): Response
    {
        if ($this->isCsrfTokenValid('delete'.$utilisateur->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($utilisateur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('utilisateurs_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/utilisateurs/_delete_form.html.twig
<form method="post" action="{{ path('utilisateurs_delete', {'id': utilisateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ utilisateur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/utilisateurs/_form.html.twig
{{ form_start(registrationForm) }}
    {{ form_widget(registrationForm) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(registrationForm) }}

templates/utilisateurs/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Utilisateurs{% endblock %}

{% block body %}
    <h1>Modifier un Utilisateur</h1>

    {{ include('utilisateurs/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('utilisateurs_index') }}">back to list</a>

    {{ include('utilisateurs/_delete_form.html.twig') }}
{% endblock %}

templates/utilisateurs/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateurs index{% endblock %}

{% block body %}
    <h1>Utilisateurs index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Identifiant</th>
                <th>Nom de famille</th>
                <th>Nom d'usage</th>
                <th>Prénoms</th>
                <th>Date de naissance</th>
                <th>Adresse principal</th>
                <th>Complément d'adresse</th>
                <th>Ville</th>
                <th>Code postale</th>
                <th>Créer par</th>
                <th>Modifier par</th>
                <th>Identifiant carte</th>
                <th>Validité</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for utilisateur in utilisateurs %}
            <tr>
                <td>{{ utilisateur.id }}</td>
                <td>{{ utilisateur.nomFamUt }}</td>
                <td>{{ utilisateur.nomUsUt }}</td>
                <td>{{ utilisateur.preUt }}</td>
                <td>{{ utilisateur.dayBirthUt ? utilisateur.dayBirthUt|date('Y-m-d') : '' }}</td>
                <td>{{ utilisateur.firstAdressUt }}</td>
                <td>{{ utilisateur.compAdressUt }}</td>
                <td>{{ utilisateur.cityUt }}</td>
                <td>{{ utilisateur.cpUt }}</td>
                <td>{{ utilisateur.createdAt ? utilisateur.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ utilisateur.updatedAt ? utilisateur.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                   {{ utilisateur.possede.id }}
                </td>

                    {% if utilisateur.possede.cardVal == true %}
                        <td style="background-color: green">
                            {{ utilisateur.possede.cardVal }}
                        </td>
                    {% else %}
                        <td style="background-color: red">
                            {{ utilisateur.possede.cardVal }}
                        </td>
                    {% endif %}

                    <td>
                    <a href="{{ path('utilisateurs_show', {'id': utilisateur.id}) }}">Voir Fiche</a>
                    <a href="{{ path('utilisateurs_edit', {'id': utilisateur.id}) }}">Modifier</a>
                </td>
                {% endfor %}
            </tr>
        </tbody>
    </table>
    <a href="{{ path('utilisateurs_new') }}">Créer nouvelle utilisateur</a>
{% endblock %}

templates/utilisateurs/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création nouvelle utilisateurs{% endblock %}

{% block stylesheets %}

    <link rel="stylesheet" href="{{ asset("assets/css/create_ut.css") }}" type="text/css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
{% endblock %}


{% block body %}

    {{ include('header.html.twig') }}

    {% form_theme registrationForm 'bootstrap_5_layout.html.twig' %}

    <div class="container-fluid">
        {% for message in app.flashes('sucess') %}
            <div class="flash-sucess">
                {{ message }}
            </div>
        {% endfor %}
        <div class="row">
            <div class="cube col col-sm-10">
                <h1>Veuillez renseigner les champs afin de créer un nouvelle  utilisateur :</h1>
                {{ form_start((registrationForm)) }}
                <div class="row">
                    <div class="col-sm-5">
                        {{ form_label(registrationForm.nomFam_ut) }}
                        {{ form_widget(registrationForm.nomFam_ut) }}
                    </div>

                    <div class="col-sm-5">
                        {{ form_label(registrationForm.nomUs_ut) }}
                        {{ form_widget(registrationForm.nomUs_ut) }}
                    </div>

                    <div class="col-sm-5">
                        {{ form_label(registrationForm.pre_ut) }}
                        {{ form_widget(registrationForm.pre_ut) }}
                    </div>

                    <div class="col-sm-5">
                        {{ form_label(registrationForm.dayBirth_ut) }}
                        {{ form_widget(registrationForm.dayBirth_ut) }}
                    </div>

                    <div class="col-sm-5">
                        {{ form_label(registrationForm.firstAdress_ut) }}
                        {{ form_widget(registrationForm.firstAdress_ut) }}
                    </div>

                    <div class="col-sm-5">
                        {{ form_label(registrationForm.compAdress_ut) }}
                        {{ form_widget(registrationForm.compAdress_ut) }}
                    </div>

                    <div class="col-sm-5">
                        {{ form_label(registrationForm.city_ut) }}
                        {{ form_widget(registrationForm.city_ut) }}
                    </div>

                    <div class="col-sm-5">
                        {{ form_label(registrationForm.cp_ut) }}
                        {{ form_widget(registrationForm.cp_ut) }}
                    </div>
                    <div class="col-sm-5">
                        {{ form_label(registrationForm.id_card) }}
                        {{ form_widget(registrationForm.id_card) }}
                    </div>
                    <div class="col-sm-5">
                        {{ form_label(registrationForm.cimetieres) }}
                        {{ form_widget(registrationForm.cimetieres) }}
                    </div>

                </div>
                {{ form_rest(registrationForm) }}

                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn enregistrer">Valider</button>
                </div>
                {{ form_end(registrationForm) }}
            </div>
            <div class="menu col-sm-auto">
                <button type="button" disabled class="btn creer">Créer</button>
                <a type="button" href="{{ path('utilisateurs_index') }}" class="btn retour">Retour</a>
            </div>
        </div>
    </div>



{% endblock %}

templates/utilisateurs/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateurs{% endblock %}

{% block body %}
    <h1>Utilisateurs</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ utilisateur.id }}</td>
            </tr>
            <tr>
                <th>NomFam_ut</th>
                <td>{{ utilisateur.nomFamUt }}</td>
            </tr>
            <tr>
                <th>NomUs_ut</th>
                <td>{{ utilisateur.nomUsUt }}</td>
            </tr>
            <tr>
                <th>Pre_ut</th>
                <td>{{ utilisateur.preUt }}</td>
            </tr>
            <tr>
                <th>DayBirth_ut</th>
                <td>{{ utilisateur.dayBirthUt ? utilisateur.dayBirthUt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>FirstAdress_ut</th>
                <td>{{ utilisateur.firstAdressUt }}</td>
            </tr>
            <tr>
                <th>CompAdress_ut</th>
                <td>{{ utilisateur.compAdressUt }}</td>
            </tr>
            <tr>
                <th>City_ut</th>
                <td>{{ utilisateur.cityUt }}</td>
            </tr>
            <tr>
                <th>Cp_ut</th>
                <td>{{ utilisateur.cpUt }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ utilisateur.createdAt ? utilisateur.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ utilisateur.updatedAt ? utilisateur.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('utilisateurs_index') }}">back to list</a>

    <a href="{{ path('utilisateurs_edit', {'id': utilisateur.id}) }}">edit</a>

    {{ include('utilisateurs/_delete_form.html.twig') }}
{% endblock %}